# Generated by Django 3.1 on 2020-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201009_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click the link above to read the post!', max_length=255),
        ),
    ]
